workflows:
  flutter-ios-simulator:
    name: Flutter iOS Simulator
    environment:
      flutter: 3.27.0
      xcode: 16.2
    scripts:
      - flutter build ios --simulator
    artifacts:
      - build/ios/iphonesimulator/Runner.app