name: Publish to App Store Connect

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    env:
      APP_STORE_CONNECT_ISSUER_ID: ${{ vars.APP_STORE_CONNECT_ISSUER_ID }}
      APP_STORE_CONNECT_KEY_IDENTIFIER: ${{ vars.APP_STORE_CONNECT_KEY_IDENTIFIER }}
      APP_STORE_CONNECT_PRIVATE_KEY: ${{ secrets.APP_STORE_CONNECT_PRIVATE_KEY }}
      CERTIFICATE_PRIVATE_KEY: ${{ secrets.CERTIFICATE_PRIVATE_KEY }}
      APP_STORE_APPLE_ID: ${{ vars.APP_STORE_APPLE_ID }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Install Codemagic CLI tools
        run: pip install codemagic-cli-tools

      - name: Set up keychain
        run: keychain initialize

      - name: Fetch signing files
        run: |
          app-store-connect fetch-signing-files $(xcode-project detect-bundle-id) \
          --type IOS_APP_STORE \
          --create

      - name: Set up signing certificate
        run: keychain add-certificates

      - name: Set up code signing settings on Xcode project
        run: xcode-project use-profiles

      - name: Increment build number
        run: |
          # Get the latest build number from App Store Connect
          LATEST_BUILD=$(app-store-connect get-latest-testflight-build-number "$APP_STORE_APPLE_ID")
          NEW_BUILD=$((LATEST_BUILD + 1))
          echo "Latest build number: $LATEST_BUILD"
          echo "New build number: $NEW_BUILD"
          
          # Update pubspec.yaml with the new build number
          sed -i '' "s/version: [0-9]\+\.[0-9]\+\.[0-9]\++[0-9]\+/version: 1.0.0+$NEW_BUILD/" pubspec.yaml
          echo "Updated pubspec.yaml with build number: $NEW_BUILD"

      - name: Build ipa for distribution
        run: |
          flutter build ipa --release --export-options-plist=$HOME/export_options.plist

      - name: Publish the app to App Store Connect
        run: |
          APP_FILE=$(find $(pwd) -name "*.ipa")
          app-store-connect publish \
          --path "$APP_FILE"